// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdfwaypygieyfzvhhatg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZndheXB5Z2lleWZ6dmhoYXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MDUwMjcsImV4cCI6MjA4NDM4MTAyN30.BAB-m8-JFNQjvHOM5VQSw3q4mKXa71C6D5p8HudBgJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});